/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

/**
 *
 * @author Abdiqani
 */
public class Dashaboard extends javax.swing.JFrame {

   Codes co=new Codes();
   public void account()
   {
       co.viewTable("SELECT * FROM `account_view`", account);
   }
    public Dashaboard() {
        initComponents();
        account();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        rSButtonGradiente2 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente3 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente4 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente5 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente6 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente7 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente1 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente13 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente14 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente15 = new rsbuttongradiente.RSButtonGradiente();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel8 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rSButtonGradiente17 = new rsbuttongradiente.RSButtonGradiente();
        jPanel3 = new javax.swing.JPanel();
        rSButtonGradiente9 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente10 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente11 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente12 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente8 = new rsbuttongradiente.RSButtonGradiente();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jPanel4 = new javax.swing.JPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        account = new javax.swing.JTable();
        rSButtonMaterialShadow1 = new RSMaterialComponent.RSButtonMaterialShadow();
        jPanel5 = new javax.swing.JPanel();
        rSButtonMaterialGradientOne3 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne5 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne4 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jPanel6 = new javax.swing.JPanel();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkGradientFocus(300);
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonGradiente2.setBackground(new java.awt.Color(255, 0, 255));
        rSButtonGradiente2.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 2, 6, 2, new java.awt.Color(255, 255, 255)));
        rSButtonGradiente2.setText("Dashboard");
        rSButtonGradiente2.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente2.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente2.setColorSecundario(new java.awt.Color(255, 0, 255));
        rSButtonGradiente2.setColorSecundarioHover(new java.awt.Color(255, 0, 255));
        rSButtonGradiente2.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        rSButtonGradiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSButtonGradiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 50));

        rSButtonGradiente3.setBackground(new java.awt.Color(255, 0, 255));
        rSButtonGradiente3.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 2, 6, 2, new java.awt.Color(255, 255, 255)));
        rSButtonGradiente3.setText("Student");
        rSButtonGradiente3.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente3.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente3.setColorSecundario(new java.awt.Color(255, 0, 255));
        rSButtonGradiente3.setColorSecundarioHover(new java.awt.Color(255, 0, 255));
        rSButtonGradiente3.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        rSButtonGradiente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSButtonGradiente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 50));

        rSButtonGradiente4.setBackground(new java.awt.Color(255, 0, 255));
        rSButtonGradiente4.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 2, 6, 2, new java.awt.Color(255, 255, 255)));
        rSButtonGradiente4.setText("Subject");
        rSButtonGradiente4.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente4.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente4.setColorSecundario(new java.awt.Color(255, 0, 255));
        rSButtonGradiente4.setColorSecundarioHover(new java.awt.Color(255, 0, 255));
        rSButtonGradiente4.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        rSButtonGradiente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSButtonGradiente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 50));

        rSButtonGradiente5.setBackground(new java.awt.Color(255, 0, 255));
        rSButtonGradiente5.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 2, 6, 2, new java.awt.Color(255, 255, 255)));
        rSButtonGradiente5.setText("Accounts");
        rSButtonGradiente5.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente5.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente5.setColorSecundario(new java.awt.Color(255, 0, 255));
        rSButtonGradiente5.setColorSecundarioHover(new java.awt.Color(255, 0, 255));
        rSButtonGradiente5.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        rSButtonGradiente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente5ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSButtonGradiente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, 50));

        rSButtonGradiente6.setBackground(new java.awt.Color(255, 0, 255));
        rSButtonGradiente6.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 2, 6, 2, new java.awt.Color(255, 255, 255)));
        rSButtonGradiente6.setText("Receipt");
        rSButtonGradiente6.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente6.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente6.setColorSecundario(new java.awt.Color(255, 0, 255));
        rSButtonGradiente6.setColorSecundarioHover(new java.awt.Color(255, 0, 255));
        rSButtonGradiente6.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        rSButtonGradiente6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente6ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSButtonGradiente6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, 50));

        rSButtonGradiente7.setBackground(new java.awt.Color(255, 0, 255));
        rSButtonGradiente7.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 2, 6, 2, new java.awt.Color(255, 255, 255)));
        rSButtonGradiente7.setText("Exam");
        rSButtonGradiente7.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente7.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente7.setColorSecundario(new java.awt.Color(255, 0, 255));
        rSButtonGradiente7.setColorSecundarioHover(new java.awt.Color(255, 0, 255));
        rSButtonGradiente7.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        rSButtonGradiente7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente7ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSButtonGradiente7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, 60));

        rSButtonGradiente1.setBackground(new java.awt.Color(255, 0, 255));
        rSButtonGradiente1.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 2, 6, 2, new java.awt.Color(255, 255, 255)));
        rSButtonGradiente1.setText("Logout");
        rSButtonGradiente1.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente1.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente1.setColorSecundario(new java.awt.Color(255, 0, 255));
        rSButtonGradiente1.setColorSecundarioHover(new java.awt.Color(255, 0, 255));
        rSButtonGradiente1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        rSButtonGradiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSButtonGradiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, -1, 50));

        rSButtonGradiente13.setBackground(new java.awt.Color(255, 0, 255));
        rSButtonGradiente13.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 2, 6, 2, new java.awt.Color(255, 255, 255)));
        rSButtonGradiente13.setText("Class");
        rSButtonGradiente13.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente13.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente13.setColorSecundario(new java.awt.Color(255, 0, 255));
        rSButtonGradiente13.setColorSecundarioHover(new java.awt.Color(255, 0, 255));
        rSButtonGradiente13.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        rSButtonGradiente13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente13ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSButtonGradiente13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, 50));

        rSButtonGradiente14.setBackground(new java.awt.Color(255, 0, 255));
        rSButtonGradiente14.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 2, 6, 2, new java.awt.Color(255, 255, 255)));
        rSButtonGradiente14.setText("Level");
        rSButtonGradiente14.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente14.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente14.setColorSecundario(new java.awt.Color(255, 0, 255));
        rSButtonGradiente14.setColorSecundarioHover(new java.awt.Color(255, 0, 255));
        rSButtonGradiente14.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        rSButtonGradiente14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente14ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSButtonGradiente14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, 50));

        rSButtonGradiente15.setBackground(new java.awt.Color(255, 0, 255));
        rSButtonGradiente15.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 2, 6, 2, new java.awt.Color(255, 255, 255)));
        rSButtonGradiente15.setText("Report");
        rSButtonGradiente15.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente15.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente15.setColorSecundario(new java.awt.Color(255, 0, 255));
        rSButtonGradiente15.setColorSecundarioHover(new java.awt.Color(255, 0, 255));
        rSButtonGradiente15.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        rSButtonGradiente15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente15ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSButtonGradiente15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, -1, 50));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 830));

        kGradientPanel2.setkGradientFocus(2310);
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOTEL MANAGEMENT SYSYTEM");
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1410, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel8.setkEndColor(new java.awt.Color(51, 255, 255));
        kGradientPanel8.setkGradientFocus(200);
        kGradientPanel8.setkStartColor(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout kGradientPanel8Layout = new javax.swing.GroupLayout(kGradientPanel8);
        kGradientPanel8.setLayout(kGradientPanel8Layout);
        kGradientPanel8Layout.setHorizontalGroup(
            kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1410, Short.MAX_VALUE)
        );
        kGradientPanel8Layout.setVerticalGroup(
            kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        jPanel1.add(kGradientPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 730));

        jTabbedPane1.addTab("Dashboard", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel6.setkEndColor(new java.awt.Color(255, 51, 255));
        kGradientPanel6.setkGradientFocus(200);
        kGradientPanel6.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        kGradientPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 80, 1410, 640));

        rSButtonGradiente17.setText("Add_Student");
        rSButtonGradiente17.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente17.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente17.setColorSecundario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente17.setColorSecundarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSButtonGradiente17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente17MouseClicked(evt);
            }
        });
        rSButtonGradiente17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente17ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonGradiente17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 30, 170, 50));

        jPanel2.add(kGradientPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 730));

        jTabbedPane1.addTab("Student", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonGradiente9.setText("Resgister-Customer");
        rSButtonGradiente9.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente9.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente9.setColorSecundario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente9.setColorSecundarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSButtonGradiente9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente9MouseClicked(evt);
            }
        });
        rSButtonGradiente9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente9ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonGradiente9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 250, 50));

        rSButtonGradiente10.setText("Responsible");
        rSButtonGradiente10.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente10.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente10.setColorSecundario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente10.setColorSecundarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSButtonGradiente10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente10MouseClicked(evt);
            }
        });
        rSButtonGradiente10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente10ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonGradiente10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 170, 50));

        rSButtonGradiente11.setText("Rooms");
        rSButtonGradiente11.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente11.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente11.setColorSecundario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente11.setColorSecundarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSButtonGradiente11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente11MouseClicked(evt);
            }
        });
        jPanel3.add(rSButtonGradiente11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 130, 50));

        rSButtonGradiente12.setText("Booking");
        rSButtonGradiente12.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente12.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente12.setColorSecundario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente12.setColorSecundarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSButtonGradiente12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente12MouseClicked(evt);
            }
        });
        jPanel3.add(rSButtonGradiente12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 140, 50));

        rSButtonGradiente8.setText("Leaving");
        rSButtonGradiente8.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente8.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente8.setColorSecundario(new java.awt.Color(51, 0, 51));
        rSButtonGradiente8.setColorSecundarioHover(new java.awt.Color(51, 0, 51));
        rSButtonGradiente8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSButtonGradiente8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente8MouseClicked(evt);
            }
        });
        jPanel3.add(rSButtonGradiente8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 140, 50));

        kGradientPanel3.setkEndColor(new java.awt.Color(255, 255, 0));
        kGradientPanel3.setkGradientFocus(200);
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1410, Short.MAX_VALUE)
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        jPanel3.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 730));

        jTabbedPane1.addTab("Subject", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel4.setkGradientFocus(200);
        kGradientPanel4.setkStartColor(new java.awt.Color(255, 153, 0));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        account.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(account);

        kGradientPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 70, 1400, 650));

        rSButtonMaterialShadow1.setBackground(new java.awt.Color(51, 0, 51));
        rSButtonMaterialShadow1.setText("Add-Account");
        rSButtonMaterialShadow1.setBackgroundHover(new java.awt.Color(51, 0, 51));
        rSButtonMaterialShadow1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        rSButtonMaterialShadow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonMaterialShadow1MouseClicked(evt);
            }
        });
        rSButtonMaterialShadow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialShadow1ActionPerformed(evt);
            }
        });
        kGradientPanel4.add(rSButtonMaterialShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 210, 60));

        jPanel4.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 730));

        jTabbedPane1.addTab("Accounts", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialGradientOne3.setText("Customer-Service");
        rSButtonMaterialGradientOne3.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonMaterialGradientOne3.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonMaterialGradientOne3.setColorSecundario(new java.awt.Color(51, 0, 51));
        rSButtonMaterialGradientOne3.setColorSecundarioHover(new java.awt.Color(51, 0, 51));
        rSButtonMaterialGradientOne3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        rSButtonMaterialGradientOne3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonMaterialGradientOne3MouseClicked(evt);
            }
        });
        jPanel5.add(rSButtonMaterialGradientOne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 310, 50));

        rSButtonMaterialGradientOne5.setText("Transfer");
        rSButtonMaterialGradientOne5.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonMaterialGradientOne5.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonMaterialGradientOne5.setColorSecundario(new java.awt.Color(51, 0, 51));
        rSButtonMaterialGradientOne5.setColorSecundarioHover(new java.awt.Color(51, 0, 51));
        rSButtonMaterialGradientOne5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        rSButtonMaterialGradientOne5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonMaterialGradientOne5MouseClicked(evt);
            }
        });
        rSButtonMaterialGradientOne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne5ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonMaterialGradientOne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 180, 50));

        rSButtonMaterialGradientOne4.setText("Register-Service");
        rSButtonMaterialGradientOne4.setColorPrimario(new java.awt.Color(51, 0, 51));
        rSButtonMaterialGradientOne4.setColorPrimarioHover(new java.awt.Color(51, 0, 51));
        rSButtonMaterialGradientOne4.setColorSecundario(new java.awt.Color(51, 0, 51));
        rSButtonMaterialGradientOne4.setColorSecundarioHover(new java.awt.Color(51, 0, 51));
        rSButtonMaterialGradientOne4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        rSButtonMaterialGradientOne4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonMaterialGradientOne4MouseClicked(evt);
            }
        });
        rSButtonMaterialGradientOne4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rSButtonMaterialGradientOne4KeyPressed(evt);
            }
        });
        jPanel5.add(rSButtonMaterialGradientOne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 320, 50));

        kGradientPanel5.setkEndColor(new java.awt.Color(255, 0, 0));
        kGradientPanel5.setkGradientFocus(100);
        kGradientPanel5.setkStartColor(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1410, Short.MAX_VALUE)
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        jPanel5.add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 740));

        jTabbedPane1.addTab("Receipt", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel7.setkEndColor(new java.awt.Color(255, 255, 0));
        kGradientPanel7.setkGradientFocus(200);
        kGradientPanel7.setkStartColor(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout kGradientPanel7Layout = new javax.swing.GroupLayout(kGradientPanel7);
        kGradientPanel7.setLayout(kGradientPanel7Layout);
        kGradientPanel7Layout.setHorizontalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1410, Short.MAX_VALUE)
        );
        kGradientPanel7Layout.setVerticalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        jPanel6.add(kGradientPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 730));

        jTabbedPane1.addTab("Report", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1405, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Class", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1405, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Level", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1405, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Exam", jPanel9);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 1410, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonGradiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_rSButtonGradiente2ActionPerformed

    private void rSButtonGradiente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente3ActionPerformed
        // TODO add your handling code here:
//        Sch_StudentTable st=new Sch_StudentTable();
//         st.setVisible(true);
//        st.setBounds(204, 220, 1598, 831);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_rSButtonGradiente3ActionPerformed

    private void rSButtonGradiente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_rSButtonGradiente4ActionPerformed

    private void rSButtonGradiente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_rSButtonGradiente5ActionPerformed

    private void rSButtonGradiente6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_rSButtonGradiente6ActionPerformed

    private void rSButtonGradiente7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente7ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(8);
    }//GEN-LAST:event_rSButtonGradiente7ActionPerformed

    private void rSButtonGradiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente1ActionPerformed

    private void rSButtonGradiente13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente13ActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_rSButtonGradiente13ActionPerformed

    private void rSButtonGradiente14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente14ActionPerformed
        // TODO add your handling code here:
             jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_rSButtonGradiente14ActionPerformed

    private void rSButtonMaterialGradientOne4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne4KeyPressed

    private void rSButtonMaterialGradientOne4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne4MouseClicked
        // TODO add your handling code here:
        Ho_ServicesTable st=new Ho_ServicesTable();
        st.setVisible(true);
        st.setBounds(204, 220, 1598, 831);
    }//GEN-LAST:event_rSButtonMaterialGradientOne4MouseClicked

    private void rSButtonMaterialGradientOne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne5ActionPerformed

    private void rSButtonMaterialGradientOne5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne5MouseClicked
        // TODO add your handling code here:
        Ho_TransferTable tt=new Ho_TransferTable();
        tt.setVisible(true);
        tt.setBounds(204, 220, 1598, 831);
    }//GEN-LAST:event_rSButtonMaterialGradientOne5MouseClicked

    private void rSButtonMaterialGradientOne3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne3MouseClicked
        // TODO add your handling code here:
        Ho_Customer_ServiceTable cst=new Ho_Customer_ServiceTable();
        cst.setVisible(true);
        cst.setBounds(204, 220, 1598, 831);
    }//GEN-LAST:event_rSButtonMaterialGradientOne3MouseClicked

    private void rSButtonMaterialShadow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMaterialShadow1MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_rSButtonMaterialShadow1MouseClicked

    private void rSButtonGradiente8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente8MouseClicked
        // TODO add your handling code here:
        Ho_LeavingTable ct=new Ho_LeavingTable();
        ct.setVisible(true);
        ct.setBounds(204, 220, 1598, 831);
    }//GEN-LAST:event_rSButtonGradiente8MouseClicked

    private void rSButtonGradiente12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente12MouseClicked

        // TODO add your handling code here:
        Ho_BookingTable bt=new Ho_BookingTable();
        bt.setVisible(true);
        bt.setBounds(204, 220, 1598, 831);
    }//GEN-LAST:event_rSButtonGradiente12MouseClicked

    private void rSButtonGradiente11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente11MouseClicked
        // TODO add your handling code here:
        Ho_RoomTable ct=new Ho_RoomTable();
        ct.setVisible(true);
        ct.setBounds(204, 220, 1598, 831);
    }//GEN-LAST:event_rSButtonGradiente11MouseClicked

    private void rSButtonGradiente10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente10ActionPerformed

    private void rSButtonGradiente10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente10MouseClicked
        // TODO add your handling code here:
        Ho_ResponsibleTable ct=new Ho_ResponsibleTable();
        ct.setVisible(true);
        ct.setBounds(204, 220, 1598, 831);
    }//GEN-LAST:event_rSButtonGradiente10MouseClicked

    private void rSButtonGradiente9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente9ActionPerformed

    private void rSButtonGradiente9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente9MouseClicked
        // TODO add your handling code here:
        Ho_CustomerTable ct=new Ho_CustomerTable();
        ct.setVisible(true);
        ct.setBounds(204, 220, 1598, 831);
    }//GEN-LAST:event_rSButtonGradiente9MouseClicked

    private void rSButtonGradiente17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente17MouseClicked

    private void rSButtonGradiente17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente17ActionPerformed
        // TODO add your handling code here:
        Sch_Student s=new Sch_Student();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
    }//GEN-LAST:event_rSButtonGradiente17ActionPerformed

    private void rSButtonGradiente15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente15ActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_rSButtonGradiente15ActionPerformed

    private void rSButtonMaterialShadow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialShadow1ActionPerformed
        // TODO add your handling code here:
        Sch_Account a=new Sch_Account();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_rSButtonMaterialShadow1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashaboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashaboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashaboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashaboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashaboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable account;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel7;
    private keeptoo.KGradientPanel kGradientPanel8;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente1;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente10;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente11;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente12;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente13;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente14;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente15;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente17;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente2;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente3;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente4;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente5;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente6;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente7;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente8;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente9;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne3;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne4;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne5;
    private RSMaterialComponent.RSButtonMaterialShadow rSButtonMaterialShadow1;
    // End of variables declaration//GEN-END:variables
}
