/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import static hospital.DoctorTable.doctortable;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author AbdiQani
 */
public class Doctor extends javax.swing.JFrame {
String gender="";
String id="";
    Codes co=new  Codes();
   public void Comboboxs(){
   
       co.fillCombo("SELECT add_no, District from address", address, "district");
       co.fillCombo("SELECT sp_no,sp_name FROM specialization", specialization, "sp_name");
       co.fillCombo("SELECT t_no, title_name from title", titlea, "title_name");
   }
    public Doctor() {
        initComponents();
        Comboboxs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rSButtonIconShadow1 = new RSMaterialComponent.RSButtonIconShadow();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dtell = new RSMaterialComponent.RSTextFieldMaterial();
        search = new RSMaterialComponent.RSTextFieldMaterial();
        specialization = new RSMaterialComponent.RSComboBoxMaterial();
        titlea = new RSMaterialComponent.RSComboBoxMaterial();
        address = new RSMaterialComponent.RSComboBoxMaterial();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dnamae = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonIconShadow1.setBackground(new java.awt.Color(255, 0, 204));
        rSButtonIconShadow1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        rSButtonIconShadow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconShadow1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonIconShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 60, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Doctor Registeration Form");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 90));

        jPanel2.setBackground(new java.awt.Color(102, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Address");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tell");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Specialization");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dactor_Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Title");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sex");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        dtell.setBackground(new java.awt.Color(102, 0, 153));
        dtell.setForeground(java.awt.Color.white);
        dtell.setCaretColor(new java.awt.Color(255, 255, 255));
        dtell.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dtell.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        dtell.setPhColor(new java.awt.Color(255, 255, 255));
        dtell.setPlaceholder("Enter Tell");
        dtell.setSelectionColor(new java.awt.Color(255, 255, 255));
        dtell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtellActionPerformed(evt);
            }
        });
        dtell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dtellKeyPressed(evt);
            }
        });
        jPanel2.add(dtell, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 260, -1));

        search.setBackground(new java.awt.Color(102, 0, 153));
        search.setForeground(java.awt.Color.white);
        search.setCaretColor(new java.awt.Color(255, 255, 255));
        search.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        search.setPhColor(new java.awt.Color(255, 255, 255));
        search.setPlaceholder("Search");
        search.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 130, -1));

        specialization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Specialization" }));
        jPanel2.add(specialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 270, -1));

        titlea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Title" }));
        jPanel2.add(titlea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 270, 40));

        address.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Address" }));
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 260, -1));

        buttonGroup1.add(male);
        male.setText("Male");
        jPanel2.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 50, 30));

        buttonGroup1.add(female);
        female.setText("Female");
        jPanel2.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 70, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\AbdiQani\\Downloads\\search.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\AbdiQani\\Downloads\\delete.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\AbdiQani\\Downloads\\Update.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\AbdiQani\\Downloads\\Save.png")); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        dnamae.setBackground(new java.awt.Color(102, 0, 153));
        dnamae.setForeground(java.awt.Color.white);
        dnamae.setCaretColor(new java.awt.Color(255, 255, 255));
        dnamae.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dnamae.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        dnamae.setPhColor(new java.awt.Color(255, 255, 255));
        dnamae.setPlaceholder("Enter Dactor Name");
        dnamae.setSelectionColor(new java.awt.Color(255, 255, 255));
        dnamae.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dnamaeKeyPressed(evt);
            }
        });
        jPanel2.add(dnamae, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 260, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 240, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 260, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 560, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconShadow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconShadow1ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_rSButtonIconShadow1ActionPerformed

    private void dtellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtellActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       if(male.isSelected()){
       gender="male";
       }
       else
          gender="female";
//        String sql = "call shaqaale(null,'"+dnamae.getText()+"','"+dtell.getText()+"','"+gender+"',(select ad_no from address where District='"+address.getSelectedItem()+"'),(select ti_no from title where ti_name='"+titlea.getSelectedItem()+"'), (select sp_no from specialization where sp_name='"+specialization.getSelectedItem()+"'),'insert')";
        String sql="Call employee_proc(null,'"+dnamae.getText()+"','"+dtell.getText()+"','"+gender+"',(select add_no from address where district='"+address.getSelectedItem()+"'),(select sp_no from specialization where sp_name='"+specialization.getSelectedItem()+"'),(select t_no from title where title_name='"+titlea.getSelectedItem()+"'),'insert')";
                if(dnamae.getText().isEmpty() || dtell.getText().isEmpty()|| gender.isEmpty()|| address.getSelectedIndex()==0 || specialization.getSelectedIndex()==0|| titlea.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Buuxi fields-ka banan!!");
                }
                else{
                co.setSql(sql);
                co.viewTable("SELECT * FROM `employee_view` ", doctortable);}
                
                
//                 try {  
//      
//        String sql = "call shaqaale(null,'"+dnamae.getText()+"','"+dtell.getText()+"','"+gender+"',(select ad_no from address where District='"+address.getSelectedItem()+"'),(select ti_no from title where ti_name='"+titlea.getSelectedItem()+"'), (select sp_no from specialization where sp_name='"+specialization.getSelectedItem()+"'),'insert')";
//        co.setSql(sql);
////        txt1.setText("");   txt2.setText(""); txt3.setSelectedIndex(0);  txt4.setSelectedIndex(0);  txt5.setSelectedIndex(0);rm.setSelected(false); rf.setSelected(false);
////        
//      }catch(Exception ex){
//      
//      }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       String sex="";
       String add="";
       String sp="";
       String tit="";
        try {
            String sql ="Select * from employee where em_no ='"+search.getText()+"' or name='"+search.getText()+"' ";
            co.search(sql);
            if(co.rs.next()){
            id=co.rs.getString("em_no");
            dnamae.setText(co.rs.getString("name"));
            dtell.setText(co.rs.getString("tell"));
            
            sex=co.rs.getString("sex");
            add=co.rs.getString("add_no");
            
            tit=co.rs.getString("t_no");
            sp=co.rs.getString("sp_no");
            
            if(sex.equals("male")){
                male.setSelected(true);
            }
            else{
            female.setSelected(true);
            }
            
                try {
                    String sql2="SELECT district FROM `address` WHERE add_no='"+add+"'";
                    co.search(sql2);
                    if(co.rs.next()){
                    address.setSelectedItem(co.rs.getString("district"));
                    }
                } catch (Exception e) {}
            
                   try {
                    String sql3="SELECT sp_name FROM specialization WHERE sp_no='"+sp+"'";
                    co.search(sql3);
                    if(co.rs.next()){
                    specialization.setSelectedItem(co.rs.getString("sp_name"));
                    }
                } catch (Exception e) {}
                   
                      try {
                    String sql4="SELECT title_name FROM title WHERE t_no='"+tit+"'";
                    co.search(sql4);
                    if(co.rs.next()){
                    titlea.setSelectedItem(co.rs.getString("title_name"));
                    }
                } catch (Exception e) {}
            
            }
            else 
                JOptionPane.showMessageDialog(null, "not found this!!");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
             if(male.isSelected()){
       gender="male";
       }
       else
          gender="female";
        String sql="Call employee_proc('"+id+"','"+dnamae.getText()+"','"+dtell.getText()+"','"+gender+"',(select add_no from address where district='"+address.getSelectedItem()+"'),"
               + "(select sp_no from specialization where sp_name='"+specialization.getSelectedItem()+"'),(select t_no from title where title_name='"+titlea.getSelectedItem()+"'),'update')";
                if(dnamae.getText().isEmpty() || dtell.getText().isEmpty()|| gender.isEmpty()|| address.getSelectedIndex()==0 || specialization.getSelectedIndex()==0|| titlea.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Buuxi fields-ka banan!!");
                }
                else{
                co.setSql(sql);
                co.viewTable("SELECT * FROM `employee_view` ", doctortable);}
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
     if(male.isSelected()){
       gender="male";
       }
       else
          gender="female";
        String sql="Call employee_proc('"+id+"','"+dnamae.getText()+"','"+dtell.getText()+"','"+gender+"',(select add_no from address where district='"+address.getSelectedItem()+"'),"
               + "(select sp_no from specialization where sp_name='"+specialization.getSelectedItem()+"'),(select t_no from title where title_name='"+titlea.getSelectedItem()+"'),'delete')";
                if(dnamae.getText().isEmpty() || dtell.getText().isEmpty()|| gender.isEmpty()|| address.getSelectedIndex()==0 || specialization.getSelectedIndex()==0|| titlea.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Buuxi fields-ka banan!!");
                }
                else{
                co.setSql(sql);
                co.viewTable("SELECT * FROM `employee_view` ", doctortable);}
    }//GEN-LAST:event_jLabel9MouseClicked

    private void dtellKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dtellKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            dtell.setEditable(false);
            jLabel12.setText("Please Enter Number Only");
        }else
        {
            dtell.setEditable(true);
        }
    }//GEN-LAST:event_dtellKeyPressed

    private void dnamaeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dnamaeKeyPressed

         char c=evt.getKeyChar();
         if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
             dnamae.setEditable(true);
//             jLabel13.setText("Please Enter Character Only");
         }
         else
        {
            dnamae.setEditable(false);
        }
    }//GEN-LAST:event_dnamaeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSComboBoxMaterial address;
    private javax.swing.ButtonGroup buttonGroup1;
    private RSMaterialComponent.RSTextFieldMaterial dnamae;
    private RSMaterialComponent.RSTextFieldMaterial dtell;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton male;
    private RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow1;
    private RSMaterialComponent.RSTextFieldMaterial search;
    private RSMaterialComponent.RSComboBoxMaterial specialization;
    private RSMaterialComponent.RSComboBoxMaterial titlea;
    // End of variables declaration//GEN-END:variables
}
