/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

/**
 *
 * @author Abdiqani
 */
public class Ho_Responsible extends javax.swing.JFrame {

    /**
     * Creates new form Ho_Responsible
     */
    public Ho_Responsible() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        rSButtonIconShadow1 = new RSMaterialComponent.RSButtonIconShadow();
        jLabel5 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        rSButtonIconShadow2 = new RSMaterialComponent.RSButtonIconShadow();
        jLabel6 = new javax.swing.JLabel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rSTextFieldMaterial5 = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonMaterialIconOne5 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne6 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne7 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne8 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSTextFieldMaterial6 = new RSMaterialComponent.RSTextFieldMaterial();
        rSTextFieldMaterial7 = new RSMaterialComponent.RSTextFieldMaterial();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSTextFieldMaterial2 = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonMaterialIconOne1 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne2 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne3 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne4 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSTextFieldMaterial3 = new RSMaterialComponent.RSTextFieldMaterial();
        rSTextFieldMaterial4 = new RSMaterialComponent.RSTextFieldMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkGradientFocus(853);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonIconShadow1.setBackground(new java.awt.Color(0, 0, 255));
        rSButtonIconShadow1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        rSButtonIconShadow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconShadow1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSButtonIconShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ResponsibleForm");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 460, -1));

        kGradientPanel3.setkGradientFocus(853);
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonIconShadow2.setBackground(new java.awt.Color(0, 0, 255));
        rSButtonIconShadow2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        rSButtonIconShadow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconShadow2ActionPerformed(evt);
            }
        });
        kGradientPanel3.add(rSButtonIconShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ResponsibleForm");
        kGradientPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 460, -1));

        kGradientPanel1.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 90));

        kGradientPanel4.setkEndColor(new java.awt.Color(51, 0, 51));
        kGradientPanel4.setkGradientFocus(150);
        kGradientPanel4.setkStartColor(new java.awt.Color(51, 0, 51));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tell");
        kGradientPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Responsible");
        kGradientPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        rSTextFieldMaterial5.setBackground(new java.awt.Color(51, 0, 51));
        rSTextFieldMaterial5.setForeground(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial5.setColorMaterial(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial5.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial5.setPhColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial5.setPlaceholder("Search ID");
        rSTextFieldMaterial5.setSelectionColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial5ActionPerformed(evt);
            }
        });
        kGradientPanel4.add(rSTextFieldMaterial5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 210, -1));

        rSButtonMaterialIconOne5.setText("Search");
        rSButtonMaterialIconOne5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        kGradientPanel4.add(rSButtonMaterialIconOne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 100, 40));

        rSButtonMaterialIconOne6.setText("Update");
        rSButtonMaterialIconOne6.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        rSButtonMaterialIconOne6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne6ActionPerformed(evt);
            }
        });
        kGradientPanel4.add(rSButtonMaterialIconOne6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 110, 40));

        rSButtonMaterialIconOne7.setText("Delete");
        rSButtonMaterialIconOne7.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        rSButtonMaterialIconOne7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne7ActionPerformed(evt);
            }
        });
        kGradientPanel4.add(rSButtonMaterialIconOne7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 110, 40));

        rSButtonMaterialIconOne8.setText("Save");
        rSButtonMaterialIconOne8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        kGradientPanel4.add(rSButtonMaterialIconOne8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 100, 40));

        rSTextFieldMaterial6.setBackground(new java.awt.Color(51, 0, 51));
        rSTextFieldMaterial6.setForeground(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial6.setColorMaterial(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial6.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial6.setPhColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial6.setPlaceholder("Enter Responsible");
        rSTextFieldMaterial6.setSelectionColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial6ActionPerformed(evt);
            }
        });
        kGradientPanel4.add(rSTextFieldMaterial6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 260, -1));

        rSTextFieldMaterial7.setBackground(new java.awt.Color(51, 0, 51));
        rSTextFieldMaterial7.setForeground(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial7.setColorMaterial(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial7.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial7.setPhColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial7.setPlaceholder("Enter Tell");
        rSTextFieldMaterial7.setSelectionColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial7ActionPerformed(evt);
            }
        });
        kGradientPanel4.add(rSTextFieldMaterial7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 260, -1));

        kGradientPanel1.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 470, 470));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 90));

        kGradientPanel2.setkEndColor(new java.awt.Color(51, 0, 51));
        kGradientPanel2.setkGradientFocus(150);
        kGradientPanel2.setkStartColor(new java.awt.Color(51, 0, 51));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tell");
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Responsible");
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        rSTextFieldMaterial2.setBackground(new java.awt.Color(51, 0, 51));
        rSTextFieldMaterial2.setForeground(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial2.setColorMaterial(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial2.setPhColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial2.setPlaceholder("Search ID");
        rSTextFieldMaterial2.setSelectionColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(rSTextFieldMaterial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 210, -1));

        rSButtonMaterialIconOne1.setText("Search");
        rSButtonMaterialIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        kGradientPanel2.add(rSButtonMaterialIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 100, 40));

        rSButtonMaterialIconOne2.setText("Update");
        rSButtonMaterialIconOne2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        rSButtonMaterialIconOne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(rSButtonMaterialIconOne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 110, 40));

        rSButtonMaterialIconOne3.setText("Delete");
        rSButtonMaterialIconOne3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        rSButtonMaterialIconOne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne3ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(rSButtonMaterialIconOne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 110, 40));

        rSButtonMaterialIconOne4.setText("Save");
        rSButtonMaterialIconOne4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        kGradientPanel2.add(rSButtonMaterialIconOne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 100, 40));

        rSTextFieldMaterial3.setBackground(new java.awt.Color(51, 0, 51));
        rSTextFieldMaterial3.setForeground(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial3.setColorMaterial(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial3.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial3.setPhColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial3.setPlaceholder("Enter Responsible");
        rSTextFieldMaterial3.setSelectionColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial3ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(rSTextFieldMaterial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 260, -1));

        rSTextFieldMaterial4.setBackground(new java.awt.Color(51, 0, 51));
        rSTextFieldMaterial4.setForeground(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial4.setColorMaterial(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial4.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial4.setPhColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial4.setPlaceholder("Enter Tell");
        rSTextFieldMaterial4.setSelectionColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial4ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(rSTextFieldMaterial4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 260, -1));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 470, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconShadow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconShadow1ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_rSButtonIconShadow1ActionPerformed

    private void rSTextFieldMaterial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial2ActionPerformed

    private void rSButtonMaterialIconOne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconOne2ActionPerformed

    private void rSButtonMaterialIconOne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconOne3ActionPerformed

    private void rSTextFieldMaterial3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial3ActionPerformed

    private void rSTextFieldMaterial4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial4ActionPerformed

    private void rSButtonIconShadow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconShadow2ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_rSButtonIconShadow2ActionPerformed

    private void rSTextFieldMaterial5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial5ActionPerformed

    private void rSButtonMaterialIconOne6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconOne6ActionPerformed

    private void rSButtonMaterialIconOne7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconOne7ActionPerformed

    private void rSTextFieldMaterial6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial6ActionPerformed

    private void rSTextFieldMaterial7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ho_Responsible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ho_Responsible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ho_Responsible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ho_Responsible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ho_Responsible().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow1;
    private RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow2;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne1;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne2;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne3;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne4;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne5;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne6;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne7;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne8;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial2;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial3;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial4;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial5;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial6;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial7;
    // End of variables declaration//GEN-END:variables
}
