
package hospital;

import javax.swing.JLabel;


public class Home extends javax.swing.JFrame {

   Codes co=new Codes();
   public void dash(String sql,String field,JLabel lb){
       try{
           co.search(sql);
           if(co.rs.next())
               lb.setText(co.rs.getString(field));
       }catch(Exception ex){
           
       }
   }
   public void display()
   {
       
       dash("SELECT COUNT(u_id) from users","COUNT(u_id)", jLabel2);
        dash("SELECT COUNT(em_no) FROM employee","COUNT(em_no)", doctor);
        dash("SELECT COUNT(p_no) from patient","COUNT(p_no)", patient);
        dash("SELECT COUNT(pc_no) from patient_checkment","COUNT(pc_no)", p_checkment);
        dash("SELECT COUNT(ck_no) FROM checkment","COUNT(ck_no)", checkment);
        dash("SELECT COUNT(pr_no) from prescription","COUNT(pr_no)", prescriptiona);
        dash("SELECT COUNT(acc_no) from accounts","COUNT(acc_no)", accounts);
        dash("SELECT COUNT(b_no) from bills","COUNT(b_no)", bills);
        dash("SELECT COUNT(rec_no) from receipt","COUNT(rec_no)", receipt);
       
       
       
       
//       
//       co.fillCombo("select p_no , name from patient", patientCompo, "name");
//       co.fillCombo("SELECT em_no , name from employee", rSComboBoxMaterial1, "name");
//       
        
//     try {
//               Class.forName("com.mysql.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/hospital", "root", "");
//            Statement std = con.createStatement();
//            ResultSet rs = std.executeQuery("select COUNT(u_id) from users");
//        
//            if (rs.next()) {
//               jLabel3.setText(rs.getString("COUNT(u_id)"));
//           }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null,e.getMessage());
//        }
//        
//         try {
//               Class.forName("com.mysql.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/hospital", "root", "");
//            Statement std = con.createStatement();
//            ResultSet rs = std.executeQuery("SELECT COUNT(em_no) FROM employee");
//        
//            if (rs.next()) {
//               doctor.setText(rs.getString("COUNT(em_no)"));
//           }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null,e.getMessage());
//        }
//         
//          try {
//               Class.forName("com.mysql.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/hospital", "root", "");
//            Statement std = con.createStatement();
//            ResultSet rs = std.executeQuery("SELECT COUNT(p_no) FROM patient");
//        
//            if (rs.next()) {
//               patient.setText(rs.getString("COUNT(p_no)"));
//           }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null,e.getMessage());
//        }
//         
    
   }
    public Home() {
        initComponents();
        display();
         //===============USers Reading ===========================//
        
        
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        rSButtonGradientIcon_new2 = new newscomponents.RSButtonGradientIcon_new();
        rSButtonGradientIcon_new3 = new newscomponents.RSButtonGradientIcon_new();
        rSButtonGradientIcon_new4 = new newscomponents.RSButtonGradientIcon_new();
        rSButtonGradientIcon_new5 = new newscomponents.RSButtonGradientIcon_new();
        rSButtonGradientIcon_new7 = new newscomponents.RSButtonGradientIcon_new();
        rSButtonGradientIcon_new8 = new newscomponents.RSButtonGradientIcon_new();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        doctor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        patient = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        p_checkment = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        checkment = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        prescriptiona = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        accounts = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        bills = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        receipt = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rSButtonGradiente1 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente2 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente3 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente4 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente5 = new rsbuttongradiente.RSButtonGradiente();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rSButtonGradiente6 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente7 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente8 = new rsbuttongradiente.RSButtonGradiente();
        jPanel5 = new javax.swing.JPanel();
        rSButtonGradiente9 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente10 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente11 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente12 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente13 = new rsbuttongradiente.RSButtonGradiente();
        jLabel14 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        rSButtonGradiente18 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente19 = new rsbuttongradiente.RSButtonGradiente();
        rSTextFieldMaterial1 = new RSMaterialComponent.RSTextFieldMaterial();
        jPanel17 = new javax.swing.JPanel();
        rSButtonGradiente16 = new rsbuttongradiente.RSButtonGradiente();
        rSButtonGradiente17 = new rsbuttongradiente.RSButtonGradiente();
        txtdoctor = new RSMaterialComponent.RSTextFieldMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 360));

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 0, 153));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 0, 153));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonGradientIcon_new2.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 3, 7, 3, new java.awt.Color(255, 255, 255)));
        rSButtonGradientIcon_new2.setText("Employee");
        rSButtonGradientIcon_new2.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new2.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new2.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new2.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        rSButtonGradientIcon_new2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradientIcon_new2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(rSButtonGradientIcon_new2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, 60));

        rSButtonGradientIcon_new3.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 3, 7, 3, new java.awt.Color(255, 255, 255)));
        rSButtonGradientIcon_new3.setText("Salary");
        rSButtonGradientIcon_new3.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new3.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new3.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new3.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PAYMENT);
        rSButtonGradientIcon_new3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradientIcon_new3ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(rSButtonGradientIcon_new3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, 60));

        rSButtonGradientIcon_new4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 3, 7, 3, new java.awt.Color(255, 255, 255)));
        rSButtonGradientIcon_new4.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\Hostel Icon Jframe\\hostel images & icon\\logout.png")); // NOI18N
        rSButtonGradientIcon_new4.setText("Logout");
        rSButtonGradientIcon_new4.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new4.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new4.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new4.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        rSButtonGradientIcon_new4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradientIcon_new4ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(rSButtonGradientIcon_new4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, -1, 60));

        rSButtonGradientIcon_new5.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 3, 7, 3, new java.awt.Color(255, 255, 255)));
        rSButtonGradientIcon_new5.setText("Dashboard");
        rSButtonGradientIcon_new5.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new5.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new5.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new5.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DASHBOARD);
        rSButtonGradientIcon_new5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradientIcon_new5ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(rSButtonGradientIcon_new5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 60));

        rSButtonGradientIcon_new7.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 3, 7, 3, new java.awt.Color(255, 255, 255)));
        rSButtonGradientIcon_new7.setText("Report");
        rSButtonGradientIcon_new7.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new7.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new7.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new7.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new7.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REPORT);
        rSButtonGradientIcon_new7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradientIcon_new7ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(rSButtonGradientIcon_new7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, 60));

        rSButtonGradientIcon_new8.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 3, 7, 3, new java.awt.Color(255, 255, 255)));
        rSButtonGradientIcon_new8.setText("Patient");
        rSButtonGradientIcon_new8.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new8.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new8.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new8.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradientIcon_new8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DASHBOARD);
        rSButtonGradientIcon_new8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradientIcon_new8ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(rSButtonGradientIcon_new8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, 60));
        kGradientPanel2.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 130, -1));
        kGradientPanel2.add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, -1));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 830));

        jPanel16.setBackground(new java.awt.Color(255, 0, 153));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HOSPITAL MANAGEMENT SYSTEM");
        jPanel16.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1410, 110));

        jPanel7.setBackground(new java.awt.Color(51, 204, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setBorder(new rojeru_san.extras.FlatShadowBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Users");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 260, 150));

        jPanel8.setBackground(new java.awt.Color(51, 255, 51));
        jPanel8.setBorder(new rojeru_san.extras.FlatShadowBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        doctor.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        doctor.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Doctor");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 260, 150));

        jPanel9.setBackground(new java.awt.Color(51, 255, 51));
        jPanel9.setBorder(new rojeru_san.extras.FlatShadowBorder());
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        patient.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        patient.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.add(patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Patient");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 260, 150));

        jPanel10.setBackground(new java.awt.Color(51, 255, 51));
        jPanel10.setBorder(new rojeru_san.extras.FlatShadowBorder());
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        p_checkment.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        p_checkment.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(p_checkment, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("P_Checkment");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 260, 150));

        jPanel11.setBackground(new java.awt.Color(51, 255, 51));
        jPanel11.setBorder(new rojeru_san.extras.FlatShadowBorder());
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        checkment.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        checkment.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.add(checkment, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Checkment");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 260, 150));

        jPanel12.setBackground(new java.awt.Color(51, 255, 51));
        jPanel12.setBorder(new rojeru_san.extras.FlatShadowBorder());
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        prescriptiona.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        prescriptiona.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.add(prescriptiona, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 30));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Prescription");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 260, 150));

        jPanel13.setBackground(new java.awt.Color(51, 255, 51));
        jPanel13.setBorder(new rojeru_san.extras.FlatShadowBorder());
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        accounts.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        accounts.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.add(accounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Accounts");
        jPanel13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 260, 150));

        jPanel14.setBackground(new java.awt.Color(51, 255, 51));
        jPanel14.setBorder(new rojeru_san.extras.FlatShadowBorder());
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        bills.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        bills.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.add(bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 30));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Bills");
        jPanel14.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jPanel7.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 260, 150));

        jPanel15.setBackground(new java.awt.Color(51, 255, 51));
        jPanel15.setBorder(new rojeru_san.extras.FlatShadowBorder());
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        receipt.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        receipt.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.add(receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 30));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Receipt");
        jPanel15.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanel7.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 260, 150));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\home.jpg")); // NOI18N
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1410, 780));

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\home.jpg")); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, 70, -1));

        jTabbedPane1.addTab("Dashboard", jPanel7);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1405, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Users", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonGradiente1.setText("Categories");
        rSButtonGradiente1.setColorPrimario(new java.awt.Color(0, 102, 255));
        rSButtonGradiente1.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente1.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente1.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                rSButtonGradiente1MouseDragged(evt);
            }
        });
        rSButtonGradiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente1MouseClicked(evt);
            }
        });
        jPanel3.add(rSButtonGradiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 110, 50));

        rSButtonGradiente2.setText("Specialization");
        rSButtonGradiente2.setColorPrimario(new java.awt.Color(0, 102, 255));
        rSButtonGradiente2.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente2.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente2.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente2MouseClicked(evt);
            }
        });
        jPanel3.add(rSButtonGradiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 140, 50));

        rSButtonGradiente3.setText("Address");
        rSButtonGradiente3.setColorPrimario(new java.awt.Color(0, 102, 255));
        rSButtonGradiente3.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente3.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente3.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente3MouseClicked(evt);
            }
        });
        jPanel3.add(rSButtonGradiente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 110, 50));

        rSButtonGradiente4.setText("Title");
        rSButtonGradiente4.setColorPrimario(new java.awt.Color(0, 102, 255));
        rSButtonGradiente4.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente4.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente4.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente4MouseClicked(evt);
            }
        });
        jPanel3.add(rSButtonGradiente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 110, 50));

        rSButtonGradiente5.setText("Doctor");
        rSButtonGradiente5.setColorPrimario(new java.awt.Color(0, 102, 255));
        rSButtonGradiente5.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente5.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente5.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente5MouseClicked(evt);
            }
        });
        rSButtonGradiente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente5ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonGradiente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 110, 50));

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\C# Pharmacy Management System\\Pharmacy Management System in C#\\dashboard.gif")); // NOI18N
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 690, 440));

        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\C# Pharmacy Management System\\Pharmacy Management System in C#\\dashboard.gif")); // NOI18N
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\C# Pharmacy Management System\\Pharmacy Management System in C#\\dashboard.gif")); // NOI18N
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 690, 280));

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\C# Pharmacy Management System\\Pharmacy Management System in C#\\dashboard.gif")); // NOI18N
        jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 800, 280));

        jTabbedPane1.addTab("Employee", jPanel3);

        jPanel4.setBackground(new java.awt.Color(51, 0, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonGradiente6.setText("Accounts");
        rSButtonGradiente6.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente6.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente6.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente6.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                rSButtonGradiente6MouseDragged(evt);
            }
        });
        rSButtonGradiente6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente6MouseClicked(evt);
            }
        });
        jPanel4.add(rSButtonGradiente6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 110, 50));

        rSButtonGradiente7.setText("Bills");
        rSButtonGradiente7.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente7.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente7.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente7.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente7MouseClicked(evt);
            }
        });
        jPanel4.add(rSButtonGradiente7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 110, 50));

        rSButtonGradiente8.setText("Receipt");
        rSButtonGradiente8.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente8.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente8.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente8.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente8MouseClicked(evt);
            }
        });
        jPanel4.add(rSButtonGradiente8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 110, 50));

        jTabbedPane1.addTab("Salary", jPanel4);

        jPanel5.setBackground(new java.awt.Color(51, 0, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonGradiente9.setText("Register_Patient");
        rSButtonGradiente9.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente9.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente9.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente9.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente9MouseClicked(evt);
            }
        });
        rSButtonGradiente9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente9ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonGradiente9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 150, 50));

        rSButtonGradiente10.setText("Patient_Checkment");
        rSButtonGradiente10.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente10.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente10.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente10.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente10MouseClicked(evt);
            }
        });
        jPanel5.add(rSButtonGradiente10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 170, 50));

        rSButtonGradiente11.setText("Checkment");
        rSButtonGradiente11.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente11.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente11.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente11.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                rSButtonGradiente11MouseDragged(evt);
            }
        });
        rSButtonGradiente11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente11MouseClicked(evt);
            }
        });
        jPanel5.add(rSButtonGradiente11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 110, 50));

        rSButtonGradiente12.setText("Visit");
        rSButtonGradiente12.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente12.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente12.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente12.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente12MouseClicked(evt);
            }
        });
        jPanel5.add(rSButtonGradiente12, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 110, 50));

        rSButtonGradiente13.setText("Prescription");
        rSButtonGradiente13.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente13.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente13.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente13.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente13MouseClicked(evt);
            }
        });
        jPanel5.add(rSButtonGradiente13, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 120, 50));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 0, 440, -1));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 90, -1));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 440, -1));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, -1, -1));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 210, 90, -1));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 440, -1));

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 420, 90, -1));

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, -1, -1));

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 627, -1, 100));

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 627, 90, 100));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 627, -1, 100));

        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\HMS ICON\\HMS ICON\\HospitalInformation.jpeg")); // NOI18N
        jPanel5.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 627, 440, 100));

        jTabbedPane1.addTab("Patient", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(51, 51, 51));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonGradiente18.setText("All Patient");
        rSButtonGradiente18.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente18.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente18.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente18.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente18MouseClicked(evt);
            }
        });
        rSButtonGradiente18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente18ActionPerformed(evt);
            }
        });
        jPanel18.add(rSButtonGradiente18, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 190, 50));

        rSButtonGradiente19.setText("Individual");
        rSButtonGradiente19.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente19.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente19.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente19.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente19MouseClicked(evt);
            }
        });
        rSButtonGradiente19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente19ActionPerformed(evt);
            }
        });
        jPanel18.add(rSButtonGradiente19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 190, 50));

        rSTextFieldMaterial1.setBackground(new java.awt.Color(51, 51, 51));
        rSTextFieldMaterial1.setForeground(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial1.setCaretColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial1.setColorMaterial(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial1.setPhColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial1.setPlaceholder("Search ");
        rSTextFieldMaterial1.setSelectionColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial1ActionPerformed(evt);
            }
        });
        jPanel18.add(rSTextFieldMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 300, -1));

        jTabbedPane2.addTab("Patient Information", jPanel18);

        jPanel17.setBackground(new java.awt.Color(51, 51, 51));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonGradiente16.setText("individual");
        rSButtonGradiente16.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente16.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente16.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente16.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente16MouseClicked(evt);
            }
        });
        rSButtonGradiente16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente16ActionPerformed(evt);
            }
        });
        jPanel17.add(rSButtonGradiente16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 110, 50));

        rSButtonGradiente17.setText("Doctor");
        rSButtonGradiente17.setColorPrimario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente17.setColorPrimarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente17.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente17.setColorSecundarioHover(new java.awt.Color(255, 0, 153));
        rSButtonGradiente17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonGradiente17MouseClicked(evt);
            }
        });
        rSButtonGradiente17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente17ActionPerformed(evt);
            }
        });
        jPanel17.add(rSButtonGradiente17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 140, 50));

        txtdoctor.setBackground(new java.awt.Color(51, 51, 51));
        txtdoctor.setForeground(new java.awt.Color(255, 255, 255));
        txtdoctor.setCaretColor(new java.awt.Color(255, 255, 255));
        txtdoctor.setColorMaterial(new java.awt.Color(255, 255, 255));
        txtdoctor.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtdoctor.setPhColor(new java.awt.Color(255, 255, 255));
        txtdoctor.setPlaceholder("Search ");
        txtdoctor.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtdoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdoctorActionPerformed(evt);
            }
        });
        jPanel17.add(txtdoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 300, -1));

        jTabbedPane2.addTab("Doctor Information", jPanel17);

        jPanel6.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 730));

        jTabbedPane1.addTab("Report", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 1410, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonGradientIcon_new5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradientIcon_new5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        display();
    }//GEN-LAST:event_rSButtonGradientIcon_new5ActionPerformed

    private void rSButtonGradientIcon_new2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradientIcon_new2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_rSButtonGradientIcon_new2ActionPerformed

    private void rSButtonGradientIcon_new3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradientIcon_new3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_rSButtonGradientIcon_new3ActionPerformed

    private void rSButtonGradientIcon_new8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradientIcon_new8ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_rSButtonGradientIcon_new8ActionPerformed

    private void rSButtonGradientIcon_new7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradientIcon_new7ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_rSButtonGradientIcon_new7ActionPerformed

    private void rSButtonGradiente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente5ActionPerformed
       
    }//GEN-LAST:event_rSButtonGradiente5ActionPerformed

    private void rSButtonGradiente5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente5MouseClicked
        // TODO add your handling code here:
        DoctorTable dt=new DoctorTable();
        dt.setVisible(true);
        dt.setBounds(205, 210, 1607, 833);
    }//GEN-LAST:event_rSButtonGradiente5MouseClicked

    private void rSButtonGradiente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente2MouseClicked
        // TODO add your handling code here:
        SpecializationTable st=new SpecializationTable();
        st.setVisible(true);
        st.setBounds(205, 210, 1607, 833);
    }//GEN-LAST:event_rSButtonGradiente2MouseClicked

    private void rSButtonGradiente1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente1MouseDragged

    private void rSButtonGradiente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente1MouseClicked
        // TODO add your handling code here:
        CategoriesTable ct=new CategoriesTable();
        ct.setVisible(true);
        ct.setBounds(205, 210, 1607, 833);
    }//GEN-LAST:event_rSButtonGradiente1MouseClicked

    private void rSButtonGradiente3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente3MouseClicked
        // TODO add your handling code here:
        AddressTable at=new AddressTable();
        at.setVisible(true);
        at.setBounds(205, 210, 1607, 833);
    }//GEN-LAST:event_rSButtonGradiente3MouseClicked

    private void rSButtonGradiente4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente4MouseClicked
        // TODO add your handling code here:
        TitleTable tt=new TitleTable();
        tt.setVisible(true);
        tt.setBounds(205, 210, 1607, 833);
    }//GEN-LAST:event_rSButtonGradiente4MouseClicked

    private void rSButtonGradiente6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente6MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente6MouseDragged

    private void rSButtonGradiente6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente6MouseClicked
        // TODO add your handling code here: 
        AccountsTable at=new AccountsTable();
        at.setVisible(true);
        at.setBounds(205, 210, 1607, 833);
    }//GEN-LAST:event_rSButtonGradiente6MouseClicked

    private void rSButtonGradiente7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente7MouseClicked
        // TODO add your handling code here:
        BillsTable bt=new BillsTable();
        bt.setVisible(true);
        bt.setBounds(205, 210, 1607, 833);
    }//GEN-LAST:event_rSButtonGradiente7MouseClicked

    private void rSButtonGradiente8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente8MouseClicked
        // TODO add your handling code here:
        ReceiptTable rt=new ReceiptTable();
        rt.setVisible(true);
        rt.setBounds(205, 210, 1607, 833);
    }//GEN-LAST:event_rSButtonGradiente8MouseClicked

    private void rSButtonGradiente9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente9MouseClicked
        // TODO add your handling code here:
        PatientTable pt = new PatientTable();
        pt.setVisible(true);
        pt.setBounds(205, 210, 1607, 833);
    }//GEN-LAST:event_rSButtonGradiente9MouseClicked

    private void rSButtonGradiente9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente9ActionPerformed

    private void rSButtonGradiente10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente10MouseClicked
        // TODO add your handling code here:
        Patient_CheckmentTable pct=new Patient_CheckmentTable();
        pct.setVisible(true);
        pct.setBounds(205, 210, 1607, 833);
    }//GEN-LAST:event_rSButtonGradiente10MouseClicked

    private void rSButtonGradiente11MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente11MouseDragged
         // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente11MouseDragged

    private void rSButtonGradiente11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente11MouseClicked
        // TODO add your handling code here:
        CheckmentTable ct=new CheckmentTable();
        ct.setVisible(true);
        ct.setBounds(205, 210, 1607, 833);
    }//GEN-LAST:event_rSButtonGradiente11MouseClicked

    private void rSButtonGradiente12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente12MouseClicked
        // TODO add your handling code here:
        VisitTable vt =new VisitTable();
        vt.setVisible(true);
        vt.setBounds(205, 210, 1607, 833);
    }//GEN-LAST:event_rSButtonGradiente12MouseClicked

    private void rSButtonGradiente13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente13MouseClicked
        // TODO add your handling code here:
        PrescriptionTable pt=new PrescriptionTable();
        pt.setVisible(true);
        pt.setBounds(205, 210, 1607, 833);
    }//GEN-LAST:event_rSButtonGradiente13MouseClicked

    private void rSButtonGradiente16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente16MouseClicked

    private void rSButtonGradiente16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente16ActionPerformed
       String sql="SELECT * FROM `employee_view` WHERE em_no='"+txtdoctor.getText()+"'";
       co.report("src\\hospital\\doctors.jrxml", sql);
    }//GEN-LAST:event_rSButtonGradiente16ActionPerformed

    private void rSButtonGradiente17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente17MouseClicked

    private void rSButtonGradiente17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente17ActionPerformed
        String sql="SELECT * FROM employee_view";
       co.report("src\\hospital\\doctors.jrxml", sql);
    }//GEN-LAST:event_rSButtonGradiente17ActionPerformed

    private void rSButtonGradiente18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente18MouseClicked

    private void rSButtonGradiente18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente18ActionPerformed
        // TODO add your handling code here:
         String sql="SELECT * FROM `patient_view`";
        co.report("src\\hospital\\Patient.jrxml", sql);
    }//GEN-LAST:event_rSButtonGradiente18ActionPerformed

    private void rSButtonGradiente19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonGradiente19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente19MouseClicked

    private void rSButtonGradiente19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente19ActionPerformed
        // TODO add your handling code here:
         String sql="SELECT * FROM `patient_view` WHERE p_no='"+rSTextFieldMaterial1.getText()+"'";
        co.report("src\\hospital\\Patient.jrxml", sql);
       
    }//GEN-LAST:event_rSButtonGradiente19ActionPerformed

    private void rSButtonGradientIcon_new4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradientIcon_new4ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_rSButtonGradientIcon_new4ActionPerformed

    private void rSTextFieldMaterial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial1ActionPerformed

    private void txtdoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdoctorActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        String sql="SELECT * FROM employee_view";
       co.report("src\\hospital\\doctors.jrxml", sql);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        String sql="SELECT * FROM `patient_view`";
        co.report("src\\hospital\\Patient.jrxml", sql);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        String sql="SELECT * FROM `patient_checkment_view`";
       co.report("src\\hospital\\patient_checkment.jrxml", sql);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        String sql="SELECT * FROM `checkment_view` ";
       co.report("src\\hospital\\checkment.jrxml", sql);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
         String sql="SELECT * FROM `prescription_view` ";
       co.report("src\\hospital\\prescription.jrxml", sql);
    }//GEN-LAST:event_jLabel18MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accounts;
    private javax.swing.JLabel bills;
    private javax.swing.JLabel checkment;
    private javax.swing.JLabel doctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel p_checkment;
    private javax.swing.JLabel patient;
    private javax.swing.JLabel prescriptiona;
    private newscomponents.RSButtonGradientIcon_new rSButtonGradientIcon_new2;
    private newscomponents.RSButtonGradientIcon_new rSButtonGradientIcon_new3;
    private newscomponents.RSButtonGradientIcon_new rSButtonGradientIcon_new4;
    private newscomponents.RSButtonGradientIcon_new rSButtonGradientIcon_new5;
    private newscomponents.RSButtonGradientIcon_new rSButtonGradientIcon_new7;
    private newscomponents.RSButtonGradientIcon_new rSButtonGradientIcon_new8;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente1;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente10;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente11;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente12;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente13;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente16;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente17;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente18;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente19;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente2;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente3;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente4;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente5;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente6;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente7;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente8;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente9;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial1;
    private javax.swing.JLabel receipt;
    private RSMaterialComponent.RSTextFieldMaterial txtdoctor;
    // End of variables declaration//GEN-END:variables
}
