
package hospital;

import javax.swing.JOptionPane;
import static mondrian.olap.Parameter.Scope.Connection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class LoginForm extends javax.swing.JFrame {

    connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    Codes co=new Codes();
    public void display(){
        co.fillCombo("SELECT id,UserType from login", usertype, "UserType");
    }
    public LoginForm() {
        initComponents();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSButtonMaterialShadow1 = new RSMaterialComponent.RSButtonMaterialShadow();
        jPanel1 = new javax.swing.JPanel();
        rSButtonIconShadow1 = new RSMaterialComponent.RSButtonIconShadow();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSTextFieldMaterial211 = new RSMaterialComponent.RSTextFieldMaterial();
        rSTextFieldMaterial3 = new RSMaterialComponent.RSTextFieldMaterial();
        usertype = new RSMaterialComponent.RSComboBoxMaterial();
        rSButtonMaterialShadow2 = new RSMaterialComponent.RSButtonMaterialShadow();
        rSButtonMaterialShadow3 = new RSMaterialComponent.RSButtonMaterialShadow();

        rSButtonMaterialShadow1.setText("rSButtonMaterialShadow1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonIconShadow1.setBackground(new java.awt.Color(51, 51, 0));
        rSButtonIconShadow1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        rSButtonIconShadow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconShadow1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonIconShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login Form");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 110));

        jPanel2.setBackground(new java.awt.Color(51, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 90));

        jPanel3.setBackground(new java.awt.Color(51, 51, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 90));

        jPanel4.setBackground(new java.awt.Color(102, 102, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UserType");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UserName");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        rSTextFieldMaterial211.setBackground(new java.awt.Color(102, 102, 0));
        rSTextFieldMaterial211.setForeground(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial211.setCaretColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial211.setColorMaterial(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial211.setPhColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial211.setPlaceholder("Enter Password");
        rSTextFieldMaterial211.setSelectionColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial211.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial211ActionPerformed(evt);
            }
        });
        jPanel4.add(rSTextFieldMaterial211, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        rSTextFieldMaterial3.setBackground(new java.awt.Color(102, 102, 0));
        rSTextFieldMaterial3.setForeground(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial3.setCaretColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial3.setColorMaterial(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial3.setPhColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial3.setPlaceholder("Enter Username");
        rSTextFieldMaterial3.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel4.add(rSTextFieldMaterial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        usertype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select UserType" }));
        jPanel4.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 250, -1));

        rSButtonMaterialShadow2.setText("Cancel");
        jPanel4.add(rSButtonMaterialShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 120, 60));

        rSButtonMaterialShadow3.setText("Login");
        rSButtonMaterialShadow3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialShadow3ActionPerformed(evt);
            }
        });
        jPanel4.add(rSButtonMaterialShadow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 120, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 500, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconShadow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconShadow1ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_rSButtonIconShadow1ActionPerformed

    private void rSTextFieldMaterial211ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial211ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial211ActionPerformed

    private void rSButtonMaterialShadow3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialShadow3ActionPerformed
//        // TODO add your handling code here:
//        String uname=rSTextFieldMaterial3.getText();
//        String pass=rSTextFieldMaterial211.getText();
//        String user=usertype.getSelectedItem().toString();
//        
//        if(uname.equals(" ")||pass.equals(" ")||user.equals("Select")){
//            JOptionPane.showMessageDialog(rootPane, "Some Fields Are Empty", "Error",1);
//            
//        }
//        else{
//            try {
//                con=connections.getconnection();
//                pst=con.PreparedStatement("select * from login where username=? and password=?");
//                pst.setString(1, uname);
//                pst.setString(2, pass);
//                rs=pst.executeQuery();
//                
//                if(rs.next()){
//                    String s1=rs.getString("UserType");
//                    if
//                }
//                
//                
//            } catch (Exception e) {
//                System.out.println(""+e);
//            }
//        }
    }//GEN-LAST:event_rSButtonMaterialShadow3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow1;
    private RSMaterialComponent.RSButtonMaterialShadow rSButtonMaterialShadow1;
    private RSMaterialComponent.RSButtonMaterialShadow rSButtonMaterialShadow2;
    private RSMaterialComponent.RSButtonMaterialShadow rSButtonMaterialShadow3;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial211;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial3;
    private RSMaterialComponent.RSComboBoxMaterial usertype;
    // End of variables declaration//GEN-END:variables

    private static class connections {

        private static connection getconnection() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public connections() {
        }
    }
}
